name: ssb
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SS_HOST }}
          username: ${{ secrets.SS_USER }}
          password: ${{ secrets.SS_PASS }}
          port: ${{ secrets.SS_PORT }}
          script: |
            cd /home/ssb/
            git checkout -f
            git pull
            npm prune
            npm install
            pm2 restart ssb
